version: '3'

services:
  # PHP Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: banking-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
    networks:
      - banking-network
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=banking-db
      - DB_PORT=3306
      - DB_DATABASE=banking
      - DB_USERNAME=banking
      - DB_PASSWORD=banking_password
    command: >
      sh -c "php artisan key:generate --force && php-fpm"
    depends_on:
      db:
        condition: service_healthy

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: banking-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: banking
      MYSQL_USER: banking
      MYSQL_PASSWORD: banking_password
      MYSQL_ROOT_PASSWORD: root_password
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - banking-data:/var/lib/mysql
    networks:
      - banking-network
    ports:
      - "33060:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: banking-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - banking-network
    depends_on:
      - app

networks:
  banking-network:
    driver: bridge

volumes:
  banking-data:
