version: '3.8'

services:
  banking-app:
    build:
      context: .
      dockerfile: Dockerfile.single
    container_name: banking-app
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - banking-storage:/var/www/html/storage
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_DATABASE=banking
      - DB_USERNAME=banking
      - DB_PASSWORD=banking_password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    stdin_open: true
    tty: true

volumes:
  banking-storage:
